<?php

/**
 * @file
 * Contains alterations for the Hel.fi tunnistamo module.
 */

declare(strict_types = 1);

use Drupal\helfi_tunnistamo\Plugin\OpenIDConnectClient\Tunnistamo;
use Drupal\openid_connect\Entity\OpenIDConnectClientEntity;
use Drupal\user\UserInterface;

/**
 * {@inheritdoc}
 */
function helfi_tunnistamo_openid_connect_post_authorize(UserInterface $account, array $context) {
  $plugin = OpenIDConnectClientEntity::load($context['plugin_id'])?->getPlugin();

  if (!$plugin instanceof Tunnistamo) {
    return;
  }
  $plugin->mapRoles($account);
}

/**
 * {@inheritdoc}
 */
function helfi_tunnistamo_openid_connect_userinfo(array &$userinfo, array $context) {
  $plugin = OpenIDConnectClientEntity::load($context['plugin_id'])?->getPlugin();

  if (!$plugin instanceof Tunnistamo) {
    return;
  }

  // If client has 'ad_groups' scope and user email is missing, replace it with
  // just some made-up address (issue with @edu.hel.fi users).
  if (in_array('ad_groups', $plugin->getClientScopes()) && empty($userinfo['email'])) {
    $userinfo['email'] = $userinfo['sub'] . '@localhost';
  }
}
