openid_connect.client.plugin.tunnistamo:
  type: openid_connect.client.plugin.[%parent.plugin]
  label: 'OpenID Connect Tunnistamo settings'
  mapping:
    is_production:
      type: integer
      label: 'Whether to use production environment or not'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client secret'
    auto_login:
      type: integer
      label: 'Whether to log in automatically on 403 pages'
    environment_url:
      type: string
      label: 'Environment URL'
    iss_allowed_domains:
      type: string
      label: 'Domains that are allowed to initiate SSO using ISS'
    client_scopes:
      type: string
      label: 'Client scopes'
    client_roles:
      type: sequence
      label: 'Client roles to automatically map to user using this client'
      sequence:
        type: string
    ad_roles_disabled_amr:
      type: sequence
      label: 'AMRs where ad role mapping is disabled'
      sequence:
        type: string
    ad_roles:
      type: sequence
      label: 'AD roles to automatically map to user using this client'
      sequence:
        type: mapping
        mapping:
          ad_role:
            type: string
          roles:
            type: sequence
            sequence:
              type: string
    debug_log:
      type: boolean
      label: 'Log ad groups for debugging'
