openid_connect.client.plugin.tunnistamo:
  type: openid_connect.client.plugin.[%parent.plugin]
  label: 'OpenID Connect Tunnistamo settings'
  mapping:
    is_production:
      type: integer
      label: 'Whether to use production environment or not'
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client secret'
