on: [push]
name: CI
env:
  SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  DRUPAL_CORE: 9.0.x
  DRUPAL_TEST_GROUPS: helfi_tunnistamo
  INSTALLER_TYPE: composer-project
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/city-of-helsinki/drupal-php-docker:7.4

    services:
      db:
        image: druidfi/db:mysql5.7-drupal
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build project
        run: |
          composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main $HOME/drupal --no-interaction --repository https://repository.drupal.hel.ninja/

      - name: Set variables
        run: |
          echo "$HOME/.config/composer/vendor/bin" >> $GITHUB_PATH
          echo "DRUPAL_ROOT=$HOME/drupal" >> $GITHUB_PATH

      - name: Setup Drupal test runner
        run: |
          composer global require tuutti/drupal-test-runner ^1.0

      - name: Run PHPCS
        run: cd $HOME/drupal && vendor/bin/phpcs public/modules/custom/ --standard=Drupal

      - name: Setup Drupal
        run: |
          drupal-tr
          drupal-tr run-drush-server &
          chromedriver --port=4444 > /dev/null 2>&1 &

      - name: Run tests
        run: TEST_RUNNER=core drupal-tr run-tests
