on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    - cron: "0 0 * * 0"
  pull_request:
  push:
    branches:
      - main
name: CI
jobs:
  tests:
    strategy:
      matrix:
        php-versions: ['8.3']
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/module-tests.yml@main
    with:
      php_version: ${{ matrix.php-versions }}
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
